### ISSUE TITLE
pip3安装失败

### ISSUE THREAD

**Issue by ghost** [littlecodersh/itchatmp#11]
python版本为3.4/3.5都试过了，pip3安装失败，报错的话是Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q1togphe/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-tfkym70u-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-q1togphe/cryptography/

**Comment by littlecodersh** [comment]
@yqnku 这是安装cryptography的报错，你可以查阅一下他的安装指南。
