### ISSUE TITLE
itchatmp.send 单纯文本的bug

### ISSUE THREAD

**Issue by ammrwu** [littlecodersh/itchatmp#12]
我用itchatmp.send('hello',fromUser)一直无法发出
itchatmp.send("@txt@xxx",fromUser) 也无法发出 
用了 itchatmp.customerservice.send(itchatmp.content.TEXT,“helloa”,{},fromUser)可以发出去
这两个应该是一样的东西 应该是additionalDict这个参数的问题

**Comment by littlecodersh** [comment]
@ammrwu 已在新版本中更新，感谢你的指出！

```python
pip install itchatmp -U
```
