### ISSUE TITLE
在无自主权限的情况下，能不能回复两次

### ISSUE THREAD

**Issue by tetsaicn** [littlecodersh/itchatmp#13]
个人订阅号无发送消息接口权限，只能回复，可看样子微信只会来访问一次第三方服务器，这样做得到么
我：测试
公众号：请 稍后
5秒后
公众号：XXXXXXX
在没有直接发送消息的权限下

**Comment by SivilTaram** [comment]
按照微信企业号的逻辑，如无主动发送能力，目前无法实现被动二次回复。你可以尝试诱导用户再次发送消息来实现你的功能，在session中存储相应的上下文。也可以使用itchat，利用个人号作为公众号的查询入口。

**Comment by tetsaicn** [comment]
什么梗，怎么诱导啊

**Comment by littlecodersh** [comment]
@tetsaicn 不能。
就从技术上来说有这样一种解决方案：模拟网页登录公众号的后台，通过网页发送。
有兴趣可以试一试。
