### ISSUE TITLE
视频发送 需要additionalDict 没地方传入

### ISSUE THREAD

**Issue by ammrwu** [littlecodersh/itchatmp#4]
发送视频            print itchatmp.send('@vid@aa.mp4', fromUser)
返回：additionalDict for type VIDEO should be: {"title" :VIDEO_TITLE, "introduction" :INTRODUCTION}

**Comment by littlecodersh** [comment]
@ammrwu 传dict进去吧，这个方法留着是为了让你发送已经获取mediaId的视频的。

**Comment by ammrwu** [comment]
发视频是这么写吗？

itchatmp.send({
                 'MsgType': itchatmp.content.VIDEO,
                 'FileDir': 'finishvideo/lsj.mp4',
                 'additionalDict':{"title":'123',"introduction":'123'}},
                  fromUser)
还是会提示
{'errcode': -10001, 'errmsg': u'\u53c2\u6570\u4e2d\u6240\u6709\u975eascii\u5b57\u7b26\u4e32\u9700\u8981\u7528Unicode\u5f62\u5f0f\u4f20\u9012\uff0c\u5982\uff1au"\u4e2d\u6587"', 'rawmsg': 'additionalDict for type VIDEO should be: {"title" :VIDEO_TITLE, "introduction" :INTRODUCTION}'}

**Comment by littlecodersh** [comment]
@ammrwu 这样：
```python
r = itchatmp.messages.upload(VIDEO, '1.mp4', {
    'title': 'title',
    'introduction': 'introduction'})
if r:
    r = itchatmp.send('@vid@1.mp4', toUserName, r['media_id'])
```
不过你需要更新一下0.0.14，13的时候我手残多打了一个逗号

**Comment by ammrwu** [comment]
@littlecodersh  thx，itchat里面直接send_video就好了 哈哈！

**Comment by littlecodersh** [comment]
@ammrwu 是的，优化的接口这周末我再做。
