### ISSUE TITLE
ImportError: cannot import name 'WSGIAdapter'

### ISSUE THREAD

**Issue by archerhu77** [littlecodersh/itchatmp#56]
python3 -m pip install itchatmp
安装后import就遇到这个错，如何解决？

**Comment by bufeii** [comment]
安装tornado版本时指定5.1版本，或者更早点的
2019年11月29日, 12:45，在 archerhu77 <notifications@github.com<mailto:notifications@github.com>> 已写:

python3 -m pip install itchatmp
安装后import就遇到这个错，如何解决？

**Comment by archerhu77** [comment]
还想请问，微信企业号在设置应用的“API接收消息”的时候，需要设置URL、Token和EncodingAESKey，其中URL应该怎样填写？是直接填写http://ip:port就可以吗？
