### ISSUE TITLE
发送视频设置 标题和简介 无法设置

### ISSUE THREAD

**Issue by ammrwu** [littlecodersh/itchatmp#6]
upload里面设置title和introduction是无效的
additionalDict 这个参数如何在send的时候传入？
     
r = itchatmp.messages.upload(itchatmp.content.VIDEO, videoObj.out_video, {
                'title': 'title test',
                'introduction': 'introduction test'})
            if r:
                r = itchatmp.send('@vid@', fromUser, r['media_id'])
这样返回的视频是没有title和introduction的 media_id里面应该没有包含标题和简介信息
media_id title description应该在send里面传入

**Comment by littlecodersh** [comment]
@ammrwu 发现了，我改改
