### ISSUE TITLE
itchatmp.send('hello',fromUser) 发不出去

### ISSUE THREAD

**Issue by ammrwu** [littlecodersh/itchatmp#7]
itchatmp.send('123',fromUser) 发不出去

**Comment by littlecodersh** [comment]
@ammrwu 未认证公众号的话没有主动发送权限的，你看一下是不是权限问题？

**Comment by ammrwu** [comment]
@littlecodersh  不是权限问题 下面这段代码 视频发出去了 但是第一句print出来说文本内容为空
 print itchatmp.send("哈哈",fromUser)
 itchatmp.send('@vid@'+r['media_id'], fromUser, r['media_id'])

{'preview': False, u'errcode': 44004, u'errmsg': u'\u6587\u672c\u6d88\u606f\u5185\u5bb9\u4e3a\u7a7a', 'rawmsg': u'empty content hint: [S3q0375ge20]'}

**Comment by Brainor** [comment]
我也遇到这个问题, 刚开始的时候提示的是文本内容为空; 后来不知道怎么折腾了之后, 错误内容变成了: api功能未授权，请确认公众号已获得该接口，可以在公众平台官网-开发者中心页中查看接口权限. 测试平台和正式个人公众号都是这样.
然后只有企业公众号才能进行认证, 认证需要300元

**Comment by ammrwu** [comment]
@Brainor  我的公众号是认证过的 发视频 图片都没有什么问题 都是主动的 就是文本发不出去

**Comment by Brainor** [comment]
@ammrwu 哦哦那应该跟我不是一个问题
