### ISSUE TITLE
在接收到语音图片消息时如何下载保存，还有微信给语音提供的识别接口的Recognition字段能用么？ 

### ISSUE THREAD

**Issue by zhtsky** [littlecodersh/itchatmp#9]

**Comment by ammrwu** [comment]
@zhtsky         file=itchatmp.messages.download(msg['MediaId'])

**Comment by zhtsky** [comment]
@ammrwu谢谢啦  不过发现个人号没有权限T_T 好在Recognition能用
{'errcode': 48001, 'errmsg': 'api功能未授权，请确认公众号已获得该接口，可以在公众平台官网-开发者中心页 中查看接口权限', 'rawmsg': 'api unauthorized hint: [rjYU70459vr29!]'}
